language : node_js
node_js :
  - "6.0"
script :
  - cd front-end
  - npm install
  - cd..
  - cd functions
  - npm install
  - npm test
  - npm run build
install:
  - npm install -g firebase-tools
after_success:
  - firebase deploy --token $FIREBASE_TOKEN


